In [1]:
#import data
import pandas as pd
df=pd.read_csv("electricity_bill_dataset.csv")

In [2]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 45345 entries, 0 to 45344
Data columns (total 12 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Fan              45345 non-null  int64
 1   Refrigerator     45345 non-null  float64
 2   AirConditioner   45345 non-null  float64
 3   Television       45345 non-null  float64
 4   Monitor          45345 non-null  float64
 5   MotorPump        45345 non-null  int64
 6   Month            45345 non-null  int64
 7   City             45345 non-null  str
 8   Company          45345 non-null  str
 9   MonthlyHours     45345 non-null  int64
 10  TariffRate       45345 non-null  float64
 11  ElectricityBill  45345 non-null  float64
dtypes: float64(6), int64(4), str(2)
memory usage: 5.5 MB

In [3]:
df.shape

(45345, 12)

In [4]:
#null value treatment
df.isna().sum()

Fan                0
Refrigerator       0
AirConditioner     0
Television         0
Monitor            0
MotorPump          0
Month              0
City               0
Company            0
MonthlyHours       0
TariffRate         0
ElectricityBill    0
dtype: int64

In [5]:
#feature selection
x=df[['Fan', 'Refrigerator', 'AirConditioner', 'Television', 'Monitor',
       'MotorPump', 'Month', 'City', 'Company', 'MonthlyHours', 'TariffRate']]
y=df['ElectricityBill']

In [6]:
x

,Fan,Refrigerator,AirConditioner,Television,Monitor,MotorPump,Month,City,Company,MonthlyHours,TariffRate
0,16,23.0,2.0,6.0,1.0,0,10,Hyderabad,Tata Power Company Ltd.,384,8.4
1,19,22.0,2.0,3.0,1.0,0,5,Vadodara,NHPC,488,7.8
2,7,20.0,2.0,6.0,7.0,0,7,Shimla,Jyoti Structure,416,7.7
3,7,22.0,3.0,21.0,1.0,0,6,Mumbai,Power Grid Corp,475,9.2
4,11,23.0,2.0,11.0,1.0,0,2,Mumbai,Ratnagiri Gas and Power Pvt. Ltd. (RGPPL),457,9.2
...,...,...,...,...,...,...,...,...,...,...,...
45340,18,22.0,3.0,22.0,1.0,0,9,Ahmedabad,Maha Transco – Maharashtra State Electricity T...,764,7.9
45341,23,23.0,2.0,6.0,12.0,0,2,New Delhi,Orient Green,572,8.5
45342,22,22.0,2.0,20.0,1.0,0,1,New Delhi,GE T&D India Limited,609,8.5
45343,8,21.0,2.0,22.0,7.0,0,12,Ratnagiri,TransRail Lighting,748,7.4
45344,8,17.0,2.0,4.0,1.0,0,1,Gurgaon,L&T Transmission & Distribution,427,8.3

In [7]:
#preprocessing
cat=[]
num=[]
for i in x.columns:
  if x[i].dtype in ['int64', 'float64']:
    num.append(i)
  else:
    cat.append(i)

Xcat=x[cat]
Xnum=x[num]

from sklearn.preprocessing import LabelEncoder,StandardScaler
le=LabelEncoder()
ss=StandardScaler()

for i in Xcat.columns:
    Xcat[i]=le.fit_transform(Xcat[i])

Xnum=pd.DataFrame(ss.fit_transform(Xnum),columns=num)

x=Xcat.join(Xnum)

In [8]:
x

,City,Company,Fan,Refrigerator,AirConditioner,Television,Monitor,MotorPump,Month,MonthlyHours,TariffRate
0,5,27,0.367281,0.773990,0.444693,-1.129725,-0.478847,0.0,1.019960,-1.069049,0.052604
1,15,13,0.915652,0.176103,0.444693,-1.650926,-0.478847,0.0,-0.432171,-0.220877,-0.987284
2,14,8,-1.277830,-1.019672,0.444693,-1.129725,1.061633,0.0,0.148681,-0.808073,-1.160598
3,7,19,-1.277830,0.176103,1.341176,1.476277,-0.478847,0.0,-0.141745,-0.326899,1.439121
4,7,20,-0.546669,0.773990,0.444693,-0.261058,-0.478847,0.0,-1.303450,-0.473697,1.439121
...,...,...,...,...,...,...,...,...,...,...,...
45340,0,12,0.732862,0.176103,1.341176,1.650010,-0.478847,0.0,0.729534,2.030040,-0.813969
45341,10,18,1.646812,0.773990,0.444693,-1.129725,2.345366,0.0,-1.303450,0.464185,0.225919
45342,10,3,1.464022,0.176103,0.444693,1.302543,-0.478847,0.0,-1.593877,0.765938,0.225919
45343,13,30,-1.095040,-0.421784,0.444693,1.650010,1.061633,0.0,1.600813,1.899553,-1.680542
45344,4,11,-1.095040,-2.813333,0.444693,-1.477192,-0.478847,0.0,-1.593877,-0.718362,-0.120711

In [9]:

#PICKLE
import pickle
with open('scaler.pkl','wb') as file1:  
    pickle.dump(ss,file1)

In [10]:
#train-test split 
from sklearn.model_selection import train_test_split
xtrain,xtest,ytrain,ytest=train_test_split(x,y,test_size=0.2,random_state=41)

In [11]:
xtrain.shape

(36276, 11)

In [13]:
xtest.shape

(9069, 11)

#TRAINING MULTIPLE MODELS TO SELECT BEST ONE

In [ ]:
#model 1- linear regression
from sklearn.linear_model import LinearRegression
lr=LinearRegression()
model=lr.fit(xtrain,ytrain)


#model 2 - k nearest neighbors
from sklearn.neighbors import KNeighborsRegressor
knn=KNeighborsRegressor(n_neighbors=5)
model=knn.fit(xtrain,ytrain)


#model 3 - decision tree regressor
from sklearn.tree import DecisionTreeRegressor
dtr=DecisionTreeRegressor()
model=dtr.fit(xtrain,ytrain)


#model 4 - random forest
from sklearn.ensemble import RandomForestRegressor
rfr=RandomForestRegressor(n_estimators=20)
model=rfr.fit(xtrain,ytrain)


#model 5 - adaboost regressor
from sklearn.linear_model import LinearRegression
from sklearn.ensemble import AdaBoostRegressor
lir=LinearRegression()
abr=AdaBoostRegressor(lir,n_estimators=25)
model=abr.fit(xtrain,ytrain)


#model 6 - support vector machine
from sklearn.svm import SVR
svr=SVR()
model=svr.fit(xtrain,ytrain)

In [15]:
#model evaluation
from sklearn.metrics import r2_score,mean_absolute_error
models = {
    "Linear Regression": lr,
    "Decision Tree": dtr,
    "Random Forest": rfr,
    "KNN": knn,
    "AdaBoost": abr,
    "SVR": svr
}

for name, model in models.items():
    y_pred = model.predict(xtest)
    print(name)
    print("R2 Score:", r2_score(ytest, y_pred))
    print("MAE:", mean_absolute_error(ytest, y_pred))
    print("-"*30)

Linear Regression
R2 Score: 0.9957027737167403
MAE: 48.70521349019814
------------------------------
Decision Tree
R2 Score: 0.9999172666053407
MAE: 1.8679347226817398
------------------------------
Random Forest
R2 Score: 0.9999776072012447
MAE: 1.631857426397849
------------------------------
KNN
R2 Score: 0.8834329653767249
MAE: 291.2142331017753
------------------------------
AdaBoost
R2 Score: 0.9957057036948421
MAE: 48.74598908003202
------------------------------
SVR
R2 Score: 0.26896466453109313
MAE: 738.5596482640664
------------------------------

#FINAL MODEL - RANDOM FOREST REGRESSOR

In [16]:
from sklearn.ensemble import RandomForestRegressor
rfr=RandomForestRegressor( n_estimators=300,
    max_depth=None,
    min_samples_split=2,
    random_state=42
)

model=rfr.fit(xtrain,ytrain)

trpred=model.predict(xtrain)
tspred=model.predict(xtest)

from sklearn.metrics import r2_score

trscore=r2_score(ytrain,trpred)
tsscore=r2_score(ytest,tspred)
print('Training Score:',trscore)
print('Testing Score:',tsscore)

Training Score: 0.9999951964053857
Testing Score: 0.9999811999145146

In [17]:
#PICKLE 
with open('model.pkl', 'wb') as file2:
    pickle.dump(model,file2)

In [18]:
with open('model.pkl' , 'rb') as file4:  
    m= pickle.load(file4)